@echo off
chcp 936 > nul
attrib +h "4)-----------[ XSeg Tools ]-------------------------------------------------------------------------------------------.bat"
attrib -h "4)++++++++++++++++[ XSeg Tools ]+++++++++++++++++++++++++++++++++++++++++++++.bat"
attrib -h "4.1)--- data_dst mask - edit.bat"
attrib -h "4.1)--- data_src mask - edit.bat"
attrib -h "4.2)--- train Xseg.bat"
attrib -h "4.3)--- data_dst whole_face mask - apply.bat"
attrib -h "4.3)--- data_dst trained mask - apply.bat"
attrib -h "4.3)--- data_src whole_face mask - apply.bat"
attrib -h "4.3)--- data_src trained mask - apply.bat"
attrib -h "4.4)--- data_dst mask - remove.bat"
attrib -h "4.4)--- data_dst trained mask - remove.bat"
attrib -h "4.4)--- data_src mask - remove.bat"
attrib -h "4.4)--- data_src trained mask - remove.bat"
attrib -h "4.5)--- data_dst mask - fetch.bat"
attrib -h "4.5)--- data_src mask - fetch.bat"